config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'

  resources :posts, only: [:create, :edit, :update, :destroy] do
    member do
      post "upvote"
      post "downvote"
    end
  end

  # Custom sign-out route
  get '/users/sign_out', to: 'custom_sessions#destroy', as: :custom_destroy_user_session

  # Set Route to User's profile and posts
  get 'user_profile_and_posts/profile', to: 'user_profile_and_posts#profile'

  # Define the custom route for editing a post under the user's profile
  patch 'users/:user_id/posts/:id/edit', to: 'user_profile_and_posts#edit', as: :edit_user_profile_post

  # For editing posts
  resources :users do
    resources :posts
  end
end

app/models/add_devise_trackable_columns_to_user.rb
class AddDeviseTrackableColumnsToUser < ApplicationRecord
    def change
        add_column :users, :sign_in_count, :integer, default: 0, null: false
        add_column :users, :current_sign_in_at, :datetime
        add_column :users, :last_sign_in_at, :datetime
        add_column :users, :current_sign_in_ip, :string
        add_column :users, :last_sign_in_ip, :string
      end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
#  extend NewsSharerCustomFeedGem::PostOrdering
  belongs_to :user
  belongs_to :category

  validates :title, presence: true
  validates :url, presence: true
  validates :category_id, presence: true

  before_save :set_default_values

  acts_as_votable
  private
  def set_default_values
    self.upvotes ||= 0
    self.downvotes ||= 0
    self.cached_votes_total ||= 0
    self.cached_votes_score ||= 0
    self.cached_votes_up ||= 0
    self.cached_votes_down ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:trackable,
         :recoverable, :rememberable, :validatable
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/custom_sessions_controller.rb
class CustomSessionsController < ApplicationController
end
class CustomSessionsController < ApplicationController
    # Make sure to include any before_action or authentication logic you need
  
    def destroy
      sign_out(current_user) # This will sign out the user using Devise
  
      # Redirect to the desired page after sign out
      redirect_to root_path # Change 'root_path' to the path of your desired page
    end
  end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Include the custom GEM
  include NewsSharerCustomFeedGem::PostOrdering

  def home
    # Fetch all posts (you may have some other logic to get the relevant posts)
    @posts = Post.all

    # Display the ordered posts by upvotes and within 24 hours
    @ordered_posts = posts_ordered_by_upvotes_and_downvotes
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # Update POST section
  before_action :set_post, only: [:edit, :update]

  # Define a new post
  def new
    @post = Post.new
  end
  # Create a new post to the database from the user
  def create
    @post = Post.new(params.permit(:title, :url, :category_id))
    @post.user_id = current_user.id
    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      puts 'Failed to save the post!'
      puts @post.errors.full_messages.inspect # Output the errors
      render :new
    end
  end
  # Delete a post from the database
  def destroy
    @post = Post.find(params[:id])
    
    if @post.destroy
      redirect_to user_profile_and_posts_profile_path
    else
      flash[:alert] = @post.errors.full_messages.inspect
      redirect_to user_profile_and_posts_profile_path
    end
  end
  # Define an upvote on what post to upvote to 
  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    redirect_to @post
  end
  # Define an downvote on what post to downvote to 
  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    redirect_to @post
  end

  # Updating the post
  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end
  private
  def set_post
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
    # Add any necessary logic here
  end
  private
  def post_params
    params.require(:post).permit(:title, :url, :category_id)
  end
end

app/controllers/user_profile_and_posts_controller.rb
class UserProfileAndPostsController < ApplicationController
    def profile
        # Here you can add any logic or data retrieval needed for the user posts page
        # @posts = Post.all # For example, getting all posts from the database
      end

      def profile
        @posts = Post.all
      end

      def redirect_to_profile
        redirect_to user_profile_and_posts_profile_path
      end




      def edit
        @user = User.find(params[:user_id])
        @post = @user.posts.find(params[:id])
        # Add any necessary logic here
        render 'edit-post' # Render the edit-post.html.erb view
      end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/custom_sessions_helper.rb
module CustomSessionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
   
end

app/helpers/user_profile_and_posts_helper.rb
module UserProfileAndPostsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>News Sharer Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    
  </head>

  <body>
  <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<!doctype html>
<html lang="en">
<head>
<!-- Title -->
<title>News Sharer Project</title>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
    <!-- Container -->
    <div class="container-fluid">
    <!-- Header -->
    <div class="header row border-bottom">
        <div class="col-6">
            <h1 class="font-italic font-weight-bold">News Sharer</h1>
        </div>
        <!-- My Posts / Logout -->
        <div class="col-6">
           
        <% if user_signed_in? %>
        <!-- class="float-end header-links" -->
            <%= link_to "Sign Out", custom_destroy_user_session_path, method: :get, class: "float-end header-links"  %>
            <%= link_to 'My posts', user_profile_and_posts_profile_path, class: "float-end header-links", style: "margin-right: 10px;" %>
      
      <%else %>
        <!-- code here for else-->
      
      <% end %>

        </div>
    </div>
    <!-- DEVISE messages-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>

    <!-- Greet the User -->
    <div class="row home-user-area border-bottom">
        <div class="col-6">
            <p> Hello <%= current_user.email.split('@').first %> </p>
            <p>You last signed in at:</p>
            <p><%= current_user.last_sign_in_at.strftime('%d/%m/%Y at %I:%M %p') %> UTC time</p>
    
            <!-- DEVISE messages -->
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>



        



        




        <div class="col-6">








        <%= form_with(model: @post, url: posts_path, format: :html, data: { turbo: false }) do |form| %>
          <!-- URL TITLE -->
          <div class="form-group">
            <%= form.text_field :title, id: "addPostTitle", class: "form-control", placeholder: "URL Title", required: true %>
          </div>
          <!-- URL LINK -->
          <div class="form-group">
            <%= form.text_field :url, id: "addPostURL", class: "form-control", placeholder: "URL Link", required: true %>
          </div>
          <!-- CATEGORY -->
          <div class="form-group">
            <%= form.select :category_id, options_for_select([
              ['Government', '1'], # Assuming 1 is the ID of the 'Government' category in the database
              ['Politics', '2'],
              ['Education', '3'],
              ['Health', '4'],
              ['Environment', '5'],
              ['Economy', '6'],
              ['Business', '7'],
              ['Sports', '8'],
              ['Funny', '9']
            ]), {}, class: "form-control" %>
          </div>

          <%= form.submit "Submit", class: "btn btn-primary" %>
        <% end %>
        
        
        









      </div>









      
      





    <!-- Content Shown -->

    <% if @ordered_posts.empty? %>
    <!-- If no posts are found-->
    <p class="border-top">No news articles posted.</p>
    <% else %>
    <!-- Loop through each post and create a card for it -->
    <h3>Posts in the last 24 hours</h3>
    <% @ordered_posts.each do |post| %>
      <div class="post row border-top">
      <div class="col">
        <div class="card shadow-lg p-3 mb-5 bg-white rounded">
          <div class="card-body">
            <!-- Post title -->
            <h5 class="card-title text-center"><%= post.title %></h5>

            <!-- Post information -->
            <p class="card-subtitle mb-2 text-muted text-center">
              Posted by <%= post.user.email if post.user_id %>
              on <%= post.created_at&.strftime('%d/%m/%Y at %I:%M %p') %> | Category: <%= post.category.category if post.category_id  %> 
            </p>
            <!-- Post URL -->
            <p class="card-body text-center">
              <!-- <%= post.url %> -->
              <a href="<%= post.url %>"> Link to the news article </a>
            </p>
            <!-- Upvote / Downvote buttons -->
            <div class="float-start">
            <!-- link_to -->
            <div class="voting-container">
              <%= button_to "Upvote", upvote_post_path(post), method: :post, class: "voting-button btn btn-success" %>
              <%= button_to "Downvote", downvote_post_path(post), method: :post, class: "voting-button btn btn-danger"%>
            </div>   
              </div>
            <!-- Upvote / Downvote counters -->
            <div class="float-end">
              <p class="card-body text-center">
                 Upvotes <span id="upvote-count-<%= post.id %>"><%= post.cached_votes_up %></span> | 
                Downvotes <span id="downvote-count-<%= post.id %>"><%= post.cached_votes_down %></span>
              </p>
            </div>      
          </div>
        </div>
      </div>
    </div>
  <% end %>
  


    <% end %>
  
  







  <%else %>
    <div class="row">
      <div class="col-12">
     
        <p class="text-center">This project is done as part of an National College of Ireland project under Cloud Application Development</p>
        <p class="text-center">This project was made by John Crawley</p>
      </div>
    </div>


    <div class="row">
      <div class="col-12">
        <div class="custom-padding-top">
          <p class="text-center">Please <%= link_to "register for a new account", new_user_registration_path %> or <%= link_to 'sign in', new_user_session_path %> to view the contents on this website.</p>
        </div>
    


      </div>
    </div>

   
  



    
  
  <% end %>
  




    </div>
  </body>
</html>

app/views/posts/_downvote_link.html.erb
# app/views/posts/_downvote_link.html.erb
<%= link_to downvote_post_path(post), method: :patch, remote: true, id: "downvote-#{post.id}" do %>
  Upvoted. Go downvote
<% end %>

app/views/posts/_upvote_count.html.erb
# app/views/posts/_like_count.html.erb
<%= post.cached_votes_score %> 

app/views/posts/_upvote_link.html.erb
# app/views/posts/_upvote_link.html.erb
<%= link_to upvote_post_path(post), method: :patch, remote: true, id: "upvote-#{post.id}" do %>
  Downvoted. Go upvote
<% end %>

app/views/posts/downvote.js.erb
// app/views/posts/downvote.js.erb
document.getElementById("upvote-link-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("downvote-link-<%= @post.id %>").innerHTML = "<%= j render "posts/downvote_link", post: @post %>";
document.getElementById("upvote-count-<%= @post.id %>").innerHTML = "<%= j render "posts/like_count", post: @post %>";
document.getElementById("downvote-count-<%= @post.id %>").innerHTML = "<%= j render "posts/dislike_count", post: @post %>";

app/views/posts/edit.html.erb
<!-- app/views/posts/edit.html.erb -->



<!doctype html>
<html lang="en">
<head>
<!-- Title -->
<title>News Sharer Project</title>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
    <!-- Container -->
    <div class="container-fluid">
    <!-- Header -->
    <div class="header row border-bottom">
        <div class="col-6">
            <h1 class="font-italic font-weight-bold">News Sharer</h1>
        </div>
        <!-- My Posts / Logout -->
        <div class="col-6">
           
        <% if user_signed_in? %>
        <!-- class="float-end header-links" -->
            <%= link_to "Sign Out", custom_destroy_user_session_path, method: :get, class: "float-end header-links"  %>
            <%= link_to 'My posts', user_profile_and_posts_profile_path, class: "float-end header-links", style: "margin-right: 10px;" %>
      
      <%else %>
        <!-- code here for else-->
      
      <% end %>

        </div>
    </div>
    <!-- DEVISE messages-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>

    <div class="Return to profile">
      <%= link_to '← Back', user_profile_and_posts_profile_path, class: "btn btn-secondary" %>
    </div>


    <!-- Content Shown -->
    <!-- Post to Edit-->

    <div class="edit-post">
    <h1>Edit News Post</h1>
    <%= form_with(model: @post, url: post_path(@post), method: :patch) do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
    
      <div class="form-group">
        <%= form.label :content %>
        <%= form.text_field :url, class: "form-control" %>
      </div>
    
      <!-- CATEGORY -->
      <div class="form-group">
        <%= form.label :category_id, "Category" %>
        <%= form.select :category_id, options_for_select([
          ['Government', '1'], # Assuming 1 is the ID of the 'Government' category in the database
          ['Politics', '2'],
          ['Education', '3'],
          ['Health', '4'],
          ['Environment', '5'],
          ['Economy', '6'],
          ['Business', '7'],
          ['Sports', '8'],
          ['Funny', '9']
        ], selected: @post.category_id), {}, class: "form-control" %>
      </div>
    
      <%= form.submit 'Update Post', class: "btn btn-primary" %>
    <% end %> 
  </div>
  

    
    




   
    


  
  







  <%else %>
    <p>Please  <%= link_to "register for a new account", new_user_registration_path%> or <%= link_to 'sign in', new_user_session_path %> to view the contents on this website.</p>
  



    
  
  <% end %>
  




    </div>
  </body>
</html>

app/views/posts/upvote.js.erb
// app/views/posts/upvote.js.erb
document.getElementById("upvote-link-<%= @post.id %>").innerHTML = "<%= j render "posts/upvote_link", post: @post %>";
document.getElementById("downvote-link-<%= @post.id %>").innerHTML = "<%= j render "posts/downvote_link", post: @post %>";
document.getElementById("upvote-count-<%= @post.id %>").innerHTML = "<%= j render "posts/like_count", post: @post %>";
document.getElementById("downvote-count-<%= @post.id %>").innerHTML = "<%= j render "posts/dislike_count", post: @post %>";

app/views/posts/upvote.js.haml
// upvote.js.haml
document.getElementById("upvote-link-#{@post.id}").innerHTML = "#{j render "posts/upvote_link", post: @post}";

app/views/user_profile_and_posts/profile.html.erb
<!doctype html>
<html lang="en">
<head>
<!-- Title -->
<title>News Sharer Project</title>
<!-- Required meta tags -->
<title>News Sharer Project - Profile</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
<body>
    <!-- Container -->
    <div class="container-fluid">
    <!-- Header -->
    <div class="header row border-bottom">
        <div class="col-6">
            <h1 class="font-italic font-weight-bold">News Sharer</h1>
        </div>
        <!-- My Posts / Logout -->
        <div class="col-6">
           
        <% if user_signed_in? %>
        <!-- class="float-end header-links" -->
            <%= link_to "Sign Out", custom_destroy_user_session_path, method: :get, class: "float-end header-links"  %>
            <%= link_to 'Home', root_path, class: "float-end header-links", style: "margin-right: 10px;" %>
      
      <%else %>
        <!-- code here for else-->
      
      <% end %>

        </div>
    </div>
    <!-- DEVISE messages-->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>

    <!-- Greet the User-->
    <div class="row">
        <div class="col-12">
            <h2> Hello <%= current_user.email.split('@').first %> </h2>
            <h3> My Posts </h3>
        </div>
    </div>

    <!-- Content Shown -->
    <div class="post row">
        <div class="col">
        <% if Post.where(user_id: current_user.id).empty? %>
          <p class="border-top border-bottom">You didn't make any news posts.</p>
        <% else %>  
        <!-- Loop over all posts with current user's id -->
        <% Post.where(user_id: current_user.id).each do |post| %>
          <div class="user_profile_my_posts card shadow-lg p-3 mb-5 bg-white rounded">
            <!-- User's Post Information-->
            <div class="user_profile_my_posts_information">
              <h4>Title: <%= post.title %></h4>
              <p>Date Posted: <%= post.created_at.strftime('%m/%d/%Y') %></p>
              <p>Category:  <%= post.category.category if post.category_id  %> </p>
              <a href="<%= post.url %>">Link to the news article</a>

              <p class="card-body text-center">
              Upvotes <span id="upvote-count-<%= post.id %>"><%= post.cached_votes_up %></span> | 
             Downvotes <span id="downvote-count-<%= post.id %>"><%= post.cached_votes_down %></span>
           </p>
            </div>
            <!-- User's Post Actions (Edit / Delete)-->
            <div class="user_profile_my_posts_actions">
              <div class="float-start">
              <a href="<%= edit_user_profile_post_path(post.user, post) %>" class="btn btn-success">Edit</a>
                <a href="#" class="btn btn-danger" data-post-id="<%= post.id %>" onclick="confirmDelete(event)" data-turbolinks="false">Delete</a>
              </div>
            </div>
          </div>
        <% end %>
        <% end %>
        <!-- JavaScript for AJAX Delete -->
        <script>
        function confirmDelete(event) {
          event.preventDefault();
          const postID = event.target.dataset.postId;
          const confirmation = confirm("Are you sure you want to delete this post?");
      
          if (confirmation) {
            // If the user confirms, send AJAX request for deletion
            const url = `/posts/${postID}`;
            const token = document.querySelector('meta[name="csrf-token"]').content;
      
            const xhr = new XMLHttpRequest();
            xhr.open("DELETE", url);
            xhr.setRequestHeader("X-CSRF-Token", token);
            xhr.setRequestHeader("Content-Type", "application/json");
            xhr.onload = function () {
              if (xhr.status === 200) {
                // Handle successful deletion
                console.log('Post deleted successfully.');

    


              } else {
                console.error('Failed to delete post.');
              }
            };
            xhr.onerror = function () {
              console.error('Error occurred while deleting post.');
            };
            xhr.send();
          }
        }
      </script>
      
        
      
            </div>
        </div>
    </div>
  
  <%else %>
    <p>Please  <%= link_to "register for a new account", new_user_registration_path%> or <%= link_to 'sign in', new_user_session_path %> to view the contents on this website.</p>
  



    
  
  <% end %>
  




    </div>
  </body>
</html>